from distutils.core import setup

packages = ["ccs",
            "ccs.bitfinex",
            "ccs.bitfinex.public",
            "ccs.bitstamp",
            "ccs.bitstamp.public",
            "ccs.bittrex",
            "ccs.bittrex.public",
            "ccs.btcc",
            "ccs.btcc.public",
            "ccs.btccpro",
            "ccs.btccpro.public",
            "ccs.btccusd",
            "ccs.btccusd.public",
            "ccs.btce",
            "ccs.btce.public",
            "ccs.bter",
            "ccs.bter.public",
            "ccs.cexio",
            "ccs.cexio.public",
            "ccs.kraken",
            "ccs.kraken.public",
            "ccs.okcoin",
            "ccs.okcoin.public",
            "ccs.okcoincn",
            "ccs.okcoincn.public",
            "ccs.okcoincom",
            "ccs.okcoincom.public",
            "ccs.poloniex"
            "ccs.poloniex.public"
            ]
setup(
    name            = 'ccs',
    packages        = packages,
    version         = '0.1.2',
    description     = 'Crypto currencies stocks (ccs) is Python package for communication with stocks which are traiding with crypto currencies. ',
    author          = 'Jan Seda',
    author_email    = 'xsedaj00@gmail.com',
    url             = 'https://github.com/Honzin/ccs',
    download_url    = 'https://github.com/Honzin/ccs/tarball/0.1.2',
    keywords        = ['bitfinex', 'bitstamp', 'bittrex', "btcc", "btce", "bter", "cexio", "kraken", "okcoin", "poloniex", "api", "crypto", "coin", "stock", "market"],
    classifiers     = [],
)
